packages:
  - packages/**

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^5.7.3
  prettier: ^3.5.1
  eslint: ^9.20.1
  eslint-config-prettier: ^10.0.1
  eslint-plugin-prettier: ^5.2.3
  '@types/eslint-config-prettier': ^6.11.3
  '@eslint/js': ^9.20.0
  typescript-eslint: ^8.24.1
  jiti: ^2.4.2
  vitest: ^3.0.6
  '@vitest/ui': ^3.0.6
  '@vitest/coverage-v8': ^3.0.6
  '@vitest/eslint-plugin': ^1.1.31
  '@pandacss/dev': ^0.51.1
  '@types/node': ^22.13.4
  '@types/react': ^19.0.10
  '@types/react-dom': ^19.0.4
  '@rsbuild/core': ^1.2.8
  '@rsbuild/plugin-react': ^1.1.0
