packages:
  - packages/**

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^5.7.2
  vitest: "^3.0.2"
  "@vitest/ui": "^3.0.2"
  "@types/node": ^22.10.7
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  "@rsbuild/core": ^1.1.8
  "@rsbuild/plugin-react": ^1.0.7
